version: "3"

tasks:
    commit:
        desc: Commit and push changes
        cmds:
            - |
                string=$(grep '^count' exercises.txt)
                exercise_count=$(echo "$string" | awk -F ':' '{print $2}' | tr -d '.')
                suffix="th"

                # commit_msg="${exercise_count}${suffix} exercise done"
                commit_msg="Waste time just to automate things"
                echo $exercise_count
                git add .
                git commit -m "${commit_msg}"
                # git push origin master

    increment:
        desc: Increment the exercise count
        cmds:
            - |
                string=$(grep '^count' exercises.txt)
                value=$(echo "$string" | awk -F ':' '{print $2}' | tr -d '.')
                exercises=$((value + 1))
                echo "count:${exercises}." > exercises.txt
